### ISSUE TITLE
enable "uk" language on server

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#328]
Airpedia has dumped "uk" mappings to the mapping wiki: https://twitter.com/airpedia/status/565066493260730369

Please enable "uk" language on the server. Currently:
* http://mappings.dbpedia.org/server/templatestatistics/uk/
* http://mappings.dbpedia.org/server/extraction/uk/

return Exception:javax.ws.rs.WebApplicationException: java.lang.Exception: language uk not configured in server

**Comment by VladimirAlexiev** [comment]
Before we can test mappings, we can't meaningfully establish the quality of the Airpedia contribution.
Eg see errors on http://mappings.dbpedia.org/index.php/Mapping_uk_talk:Infobox_Settlement

**Comment by alexandrutodor** [comment]
Hi Vladimir,

The namespaces az, hy, ro, sv and uk are present on the wiki and implemented in the code but aren't fully functional yet because the server where mappings.dbpedia.org is hosted needs to be updated to a newer Debian version in order to be able to run the newer server module on it. In the meantime mappings can be added to the wiki, validation and statistics won't work though. This will be fixed as soon as the server is updated.

**Comment by jimkont** [comment]
Hi @alexandrutodor this is now fixed for all new languages
