### ISSUE TITLE
Problems with dbprop/dbowl : leaderName/dbpedia-owl:leaderTitle

### ISSUE THREAD

**Issue by D063520** [dbpedia/extraction-framework#402]
I have problems with the properties dbprop:leaderName, dbprop:leaderTitel since if there are multiple entries one can not associate the name with the corresponding title. For example look at:
http://dbpedia.org/page/Germany
The mapping is clear in the Wikipedia inbox:
https://en.wikipedia.org/wiki/Germany
but not anymore in dbpedia.

The biggest problem is that there is no triple like "dbpedia:Germany, president, dbpedia:Joachim_Gauck". So one can for example not easily query for the presidents of the european states or something like that.
I hope this is the right place for this issue. If not, sorry for that, and please tell me a better place.

**Comment by jimkont** [comment]
Hi @D063520 

Missing information in DBpedia is most times due to incorrect or missing mappings in the DBpedia mappings wiki (http://mappings.dbpedia.org).
The general approach is to find which template in Wikipedia has the information you want and create or improve that mapping. Changes should show up in DBpedia Live soon and in the next static release

also take a look at our faq
http://wiki.dbpedia.org/faq?field_faq_category_tid%5B%5D=63
