### ISSUE TITLE
Parsing of wikidata {{#property:xxx}} templates

### ISSUE THREAD

**Issue by vanthome** [dbpedia/extraction-framework#406]
Looking at this page, I see that the currency is: `dbr:{{` which is obviously wrong.

**Comment by VladimirAlexiev** [comment]
We got 2 bad, 1 good:
```
dbo:currency	dbr:{{
dbp:currency	dbr:{{
dbp:currencyCode	"USD"
```

Looking [at the source page](https://en.wikipedia.org/w/index.php?title=United_States&action=edit), the reason is that en.wiki started using Wikidata props. The DBpedia extractor doesn't know about it and tries to extract this as a normal link, and stops at `#`
```
|currency = [[{{#property:p38}}]] ($)
|currency_code = USD
```

@jimkont: this is high prio, since the biggest wikipedia started using wikidata at least for some props.
