### ISSUE TITLE
Problem with http://dbpedia.org/resource/Pistol

### ISSUE THREAD

**Issue by Hronom** [dbpedia/extraction-framework#430]
Hello everyone!

I use dumps from http://downloads.dbpedia.org/2015-04/core-i18n/

So at dumps `instance-types-en-uris_el.nt` and `instance-types-en-uris_ru.nt` I have next triples:
```
instance-types-en-uris_el.nt(35962): <http://dbpedia.org/resource/Pistol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Book> .
instance-types-en-uris_ru.nt(9112): <http://dbpedia.org/resource/Pistol> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Book> .
```
Looks like type `http://dbpedia.org/ontology/Book` is wrong for `http://dbpedia.org/resource/Pistol`.

I check version of this dumps in http://downloads.dbpedia.org/2015-10/core-i18n/ and http://downloads.dbpedia.org/current/core-i18n/ and they also contains this error.

Please can you check how this can happen. And maybe fix that.

**Comment by jimkont** [comment]
This was due to incorrect mappings that messed with the types
http://mappings.dbpedia.org/index.php/Mapping_ru:%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0
http://mappings.dbpedia.org/index.php/Mapping_el:%CE%A0%CE%B1%CF%81%CE%B1%CF%80%CE%BF%CE%BC%CF%80%CE%AD%CF%82

they are now removed with a warning

see also #422
