### ISSUE TITLE
dbo:Library is unsatisfiable

### ISSUE THREAD

**Issue by LorenzBuehmann** [dbpedia/extraction-framework#542]
See the explanation why:

![image](https://user-images.githubusercontent.com/976029/35454331-e2a54b90-02cd-11e8-9966-617cf45da5aa.png)

**Comment by mgns** [comment]
I removed the SubClassOf dbo:Building relationship, because not every library is a building. This fixes the inconsistency inside the ontology. Disclaimer: when loading the ontology with DBpedia instance data, there may occur inconsistencies, in particular because of domain, range and disjoint class restrictions.
