### ISSUE TITLE
Starring property missing in some films

### ISSUE THREAD

**Issue by ottaviovanini** [dbpedia/extraction-framework#552]
Good evening, I don't know if this is the right place to report a problem about some missing properties.
I just started studying SPARQL and I'm trying to do some queries on https://dbpedia.org/sparql and I noticed that some films do not have the property dbo:starring, such as http://dbpedia.org/resource/The_Matrix_Revolutions .
I would like to know why this property is missing? Does it depend on a problem of the infobox data extraction ?

Thank you very much and congratulations for the great work you are doing.

**Comment by mgns** [comment]
Thank you for the pointer that might be because of the `Plain list` template used for listing the actors.

**Comment by JJ-Author** [comment]
this is fixed in the template-test branch see the output below


http://dbpedia.org/resource/The_Matrix_Revolutions | http://dbpedia.org/ontology/starring | http://dbpedia.org/resource/Jada_Pinkett_Smith | http://en.wikipedia.org/wiki/The_Matrix_Revolutions?oldid=847227139&ns=0
-- | -- | -- | --
http://dbpedia.org/resource/The_Matrix_Revolutions | http://dbpedia.org/ontology/starring | http://dbpedia.org/resource/Hugo_Weaving | http://en.wikipedia.org/wiki/The_Matrix_Revolutions?oldid=847227139&ns=0
http://dbpedia.org/resource/The_Matrix_Revolutions | http://dbpedia.org/ontology/starring | http://dbpedia.org/resource/Carrie-Anne_Moss | http://en.wikipedia.org/wiki/The_Matrix_Revolutions?oldid=847227139&ns=0
http://dbpedia.org/resource/The_Matrix_Revolutions | http://dbpedia.org/ontology/starring | http://dbpedia.org/resource/Laurence_Fishburne | http://en.wikipedia.org/wiki/The_Matrix_Revolutions?oldid=847227139&ns=0
http://dbpedia.org/resource/The_Matrix_Revolutions | http://dbpedia.org/ontology/starring | http://dbpedia.org/resource/Keanu_Reeves | http://en.wikipedia.org/wiki/The_Matrix_Revolutions?oldid=847227139&ns=0

**Comment by gaurav** [comment]
I've noticed that these dbo:starring triples haven't made it to Virtuoso yet (http://dbpedia.org/page/The_Matrix_Revolutions). Have these changes been merged into master yet?

**Comment by JJ-Author** [comment]
not yet. but @chile12 is contributing some of his valuable experience in his leisure time to merge some of the features from the template-test branch back to the master. To the best of my knowledge this should also include this fix.
