### ISSUE TITLE
DBPedia extraction for ConceptNet

### ISSUE THREAD

**Issue by gyankos** [dbpedia/extraction-framework#556]
After downloading some recent Wikipedia Dump for generating a more recent version of DBPedia, i used the following command to start generating the dataset:

> ../run extraction extraction.default.properties

Nevertheless, during the extraction phase I encounter some errors like:

     Exception; en; Main Extraction at 698:45.733s for 74 datasets; Main Extraction failed for instance http://dbpedia.org/resource/1900_(film): Tried to convert inconvertible unit
     java.lang.UnsupportedOperationException: Tried to convert inconvertible unit

or even

     Couldn't load property mapping on page Mapping en:Infobox drug. Details: Unknown property type   CombineSimpleMapping on page title=Infobox drug;ns=204/Mapping en/Mapping en;language:wiki=mappings,locale=en
     java.lang.IllegalArgumentException: Unknown property type CombineSimpleMapping on page title=Infobox drug;ns=204/Mapping en/Mapping en;language:wiki=mappings,locale=en
	at        org.dbpedia.extraction.mappings.MappingsLoader$.org$dbpedia$extraction$mappings$MappingsLoader$$loadPropertyMapping(MappingsLoader.scala:214)
	at org.dbpedia.extraction.mappings.MappingsLoader$$anonfun$org$dbpedia$extraction$mappings$MappingsLoader$$loadPropertyMappings$1$$anonfun$apply$4.apply(MappingsLoader.scala:124)

Is this the expected behaviour? Since we're here, is there a faster way to generate only the following files ?

- instance_types_en.tql.bz2
- interlanguage_links_en.tql.bz2
- mappingbased_objects_en.tql.bz2

**Comment by JJ-Author** [comment]
w.r.t to the second exception. the mapping uses a new mapping language feature which is implemented in the template-test branch but not merged to the master, yet. you can use this new branch and the error should get away. 

w.r.t to the first exception: This was a simple a bug in a if clause of the extraction framework. It tried to convert/normalize the budget value but of course it does not make sense to convert a currency. It is also fixed in template-test branch. 

considering your question: you can configure the extractors to be used in a properties file of dump package. I guess you only need InterLanguageLinksExtractor and MappingExtractor
